apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  clusterIP: None
  ports:
  - port: 9042
    targetPort: 9042
    name: cql
  selector:
    app: cassandra
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:latest
        ports:
        - containerPort: 9042
          name: cql
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "babbly_cluster"
        - name: MAX_HEAP_SIZE
          value: "1024M"
        - name: HEAP_NEWSIZE
          value: "256M"
        readinessProbe:
          tcpSocket:
            port: 9042
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 9042
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
        - name: post-init-scripts
          mountPath: /docker-entrypoint-initdb.d/post
        - name: comment-init-scripts
          mountPath: /docker-entrypoint-initdb.d/comment
        - name: like-init-scripts
          mountPath: /docker-entrypoint-initdb.d/like
      volumes:
      - name: cassandra-data
        persistentVolumeClaim:
          claimName: cassandra-data
      - name: post-init-scripts
        emptyDir: {}
      - name: comment-init-scripts
        emptyDir: {}
      - name: like-init-scripts
        emptyDir: {} 