apiVersion: v1
kind: Secret
metadata:
  name: auth0-secrets
type: Opaque
stringData:
  AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
  AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
  AUTH0_CLIENT_SECRET: "${AUTH0_CLIENT_SECRET}"
  AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}"
  AUTH0_SECRET: "${AUTH0_SECRET}"
  AUTH0_ISSUER_BASE_URL: "${AUTH0_ISSUER_BASE_URL}"
---
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-secrets
type: Opaque
stringData:
  CASSANDRA_HOSTS: "${CASSANDRA_HOSTS}"
  CASSANDRA_USERNAME: "${CASSANDRA_USERNAME}"
  CASSANDRA_PASSWORD: "${CASSANDRA_PASSWORD}" 