name: Deploy to AKS

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Authenticate to AKS
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy infrastructure components
      run: |
        echo "Deploying secrets..."
        kubectl apply -f infrastructure/k8s/secrets.yaml --namespace=default
        
        echo "Deploying Kafka and Zookeeper..."
        kubectl apply -f infrastructure/k8s/kafka-zookeeper.yaml --namespace=default
        
        echo "Deploying Cassandra..."
        kubectl apply -f infrastructure/k8s/cassandra.yaml --namespace=default
        
        echo "Checking if Cassandra pod exists and restarting if needed..."
        if kubectl get pod cassandra-0 --namespace=default >/dev/null 2>&1; then
          echo "Existing Cassandra pod found, deleting to apply new configuration..."
          kubectl delete pod cassandra-0 --namespace=default --wait=false || true
        fi
        
        echo "Deploying Prometheus..."
        kubectl apply -f infrastructure/k8s/prometheus.yaml --namespace=default
        
        echo "Deploying Grafana..."
        kubectl apply -f infrastructure/k8s/grafana.yaml --namespace=default

    - name: Wait for infrastructure to be ready
      run: |
        echo "Waiting for Zookeeper to be ready..."
        kubectl wait --for=condition=available --timeout=300s deployment/zookeeper --namespace=default
        
        echo "Waiting for Kafka to be ready..."
        kubectl wait --for=condition=available --timeout=300s deployment/kafka --namespace=default
        
        echo "Waiting for Cassandra StatefulSet to be ready..."
        kubectl wait --for=jsonpath='{.status.readyReplicas}'=1 --timeout=300s statefulset/cassandra --namespace=default || echo "StatefulSet timeout, continuing..."
        
        echo "Checking Cassandra pod status..."
        kubectl get pods -l app=cassandra --namespace=default
        kubectl get statefulset cassandra --namespace=default
        
        echo "Waiting for Cassandra pod to be ready (extended timeout)..."
        kubectl wait --for=condition=ready --timeout=600s pod -l app=cassandra --namespace=default || {
          echo "Cassandra still not ready, checking detailed status..."
          kubectl describe pod -l app=cassandra --namespace=default
          kubectl logs -l app=cassandra --namespace=default --tail=100
          kubectl get events --namespace=default --field-selector involvedObject.name=cassandra-0
          echo "Continuing despite Cassandra not being ready..."
        }
        
        echo "Waiting for Prometheus to be ready..."
        kubectl wait --for=condition=available --timeout=600s deployment/prometheus --namespace=default || {
          echo "Prometheus not ready, checking status..."
          kubectl get pods -l app=prometheus --namespace=default
          kubectl describe pod -l app=prometheus --namespace=default
          kubectl logs -l app=prometheus --namespace=default --tail=50
          echo "Continuing despite Prometheus not being ready..."
        }
        
        echo "Waiting for Grafana to be ready..."
        kubectl wait --for=condition=available --timeout=600s deployment/grafana --namespace=default || {
          echo "Grafana not ready, checking status..."
          kubectl get pods -l app=grafana --namespace=default
          kubectl describe pod -l app=grafana --namespace=default
          kubectl logs -l app=grafana --namespace=default --tail=50
          echo "Continuing despite Grafana not being ready..."
        }

    - name: Deploy microservices
      run: |
        echo "Deploying Auth Service..."
        kubectl apply -f babbly-auth-service/k8s/ --namespace=default
        
        echo "Deploying User Service..."
        kubectl apply -f babbly-user-service/k8s/ --namespace=default
        
        echo "Deploying Post Service..."
        kubectl apply -f babbly-post-service/k8s/ --namespace=default
        
        echo "Deploying Comment Service..."
        kubectl apply -f babbly-comment-service/k8s/ --namespace=default
        
        echo "Deploying Like Service..."
        kubectl apply -f babbly-like-service/k8s/ --namespace=default

    - name: Deploy API Gateway
      run: |
        echo "Deploying API Gateway..."
        kubectl apply -f babbly-api-gateway/k8s/ --namespace=default

    - name: Deploy Frontend
      run: |
        echo "Deploying Frontend..."
        kubectl apply -f babbly-frontend/k8s/ --namespace=default

    - name: Wait for deployments to be ready
      run: |
        echo "Waiting for all deployments to be ready..."
        kubectl wait --for=condition=available --timeout=300s deployment/auth-service --namespace=default
        kubectl wait --for=condition=available --timeout=300s deployment/user-service --namespace=default
        kubectl wait --for=condition=available --timeout=300s deployment/post-service --namespace=default
        kubectl wait --for=condition=available --timeout=300s deployment/comment-service --namespace=default
        kubectl wait --for=condition=available --timeout=300s deployment/like-service --namespace=default
        kubectl wait --for=condition=available --timeout=300s deployment/api-gateway --namespace=default
        kubectl wait --for=condition=available --timeout=300s deployment/frontend --namespace=default

    - name: Get service information
      run: |
        echo "Getting service information..."
        kubectl get services --namespace=default
        echo "Getting pod status..."
        kubectl get pods --namespace=default
        echo "Getting external IP for API Gateway..."
        kubectl get service api-gateway --namespace=default
        echo "Getting monitoring services..."
        kubectl get service prometheus grafana --namespace=default

    - name: Verify deployment
      run: |
        echo "Verifying Kafka topics..."
        kubectl exec deployment/kafka --namespace=default -- kafka-topics --bootstrap-server localhost:9092 --list || true
        
        echo "Checking service connectivity..."
        kubectl get endpoints --namespace=default 